version: '3'
services:
  flasky:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0'
    command: flask run --host=0.0.0.0